name: Tag

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  tagging:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.62.0
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          DEFAULT_BUMP: minor
          RELEASE_BRANCHES: main
          WITH_V: true
